version: "2"
services:
  web:
    build: .
    depends_on: 
      - db
    volumes:
      - ./www:/var/www/html
    ports:
      - 80
    
  db:
    image: mariadb:10.4
    environment:
      MYSQL_DATABASE: file_sqli
      MYSQL_USER: panghu
      MYSQL_PASSWORD: panghu404
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]

